name: OCPI CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "**" ]

permissions:
    contents: read

jobs:
    build:

        concurrency: ocpi-ci

        runs-on: ubuntu-latest

        steps:
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Checkout IZIVIA OCPI toolkit library code from GH
                uses: actions/checkout@v3

            -   name: Build annotation processor with Gradle
                uses: gradle/gradle-build-action@v2.8.1
                with:
                    gradle-version: wrapper
                    arguments: :annotation-processor:build
                    cache-read-only: ${{ github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/main' }}

            -   name: Build OCPI toolkit with Gradle
                uses: gradle/gradle-build-action@v2.8.1
                with:
                    gradle-version: wrapper
                    arguments: build
                    cache-read-only: ${{ github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/main' }}
