name: OCPI Publish

on:
    push:
        tags:
            - "R-*"

permissions:
    contents: read

jobs:
    build:

        concurrency: ocpi-publish

        runs-on: ubuntu-latest

        steps:
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Checkout IZIVIA OCPI toolkit library code from GH
                uses: actions/checkout@v3

            -   name: Publish OCPI annotation processor to maven local
                uses: gradle/gradle-build-action@v2.8.1
                env:
                    VERSION: ${{ github.ref }}
                with:
                    gradle-version: wrapper
                    arguments: :annotation-processor:publishToMavenLocal
                    cache-read-only: ${{ github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/main' }}

            -   name: Build OCPI toolkit
                uses: gradle/gradle-build-action@v2.8.1
                env:
                    VERSION: ${{ github.ref }}
                    SONATYPE_USERNAME: ${{ secrets.DELIVERY_SONATYPE_USERNAME }}
                    SONATYPE_PASSWORD: ${{ secrets.DELIVERY_SONATYPE_PASSWORD }}
                    GPG_PRIVATE_KEY: ${{ secrets.DELIVERY_GPG_SECRET_KEY }}
                    GPG_PASSPHRASE: ${{ secrets.DELIVERY_GPG_KEY_PASSPHRASE }}
                with:
                    gradle-version: wrapper
                    arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
                    cache-read-only: ${{ github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/main' }}
